### PR TITLE
Add an update method for the GIT repositories

### PR DESCRIPTION
**Pull request by E-HO**
So the same script can be used to only update (pull) the git repositories after the initial install.

By the way, are the SaaS-tools and install script for those tools compatible with Ubuntu 17.10 and Odoo 11 ? Running it always give a pip module "xmlrpc.client" not available.

### CODE REVIEW

**Comment by yelizariev** [comment]
New command seems to be the same as existing GIT_PULL

**Comment by E-HO** [comment]
argh, completely missed this option ...

**Comment by E-HO** [comment]
Maybe just add a condition `if [[ "$CLONE_OCA" == "yes" ]] || [[ "$CLONE_IT_PROJECTS_LLC" == "yes" ]] ...` for the lines about the REPOS and tha git install / clone command to run that part just if we need to clone someting ? And the GIT_PULL section just after this section ?

**Comment by yelizariev** [comment]
GIT_PULL updates all git folders in addons and odoo path. No need to check CLONE_OCA, CLONE_IT_PROJECTS_LLC variables

**Pull request closed without merging**
